import { colors } from 'tailwindcss/defaultTheme'

export default {
  '@red-6': colors.red[600],
  '@blue-6': colors.blue[600],
  '@pink-6': colors.pink[600],
  '@green-6': colors.green[600],
  '@orange-6': colors.orange[600],
  '@yellow-6': colors.yellow[600],
  '@purple-6': colors.purple[600],
  '@primary-color': colors.blue[600],
  '@font-size-sm': '14px',
  '@font-size-base': '16px',
  '@btn-font-size-sm': '14px',
  '@btn-height-sm': '32px',
  '@btn-height-base': '42px',
  '@btn-height-lg': '52px',
  '@radio-size': '18px',
  '@checkbox-size': '18px',
  '@badge-status-size': '11px',
  '@input-height-sm': '32px',
  '@input-height-base': '40px',
  '@input-height-lg': '48px',
  '@input-padding-vertical-sm': '4px',
  '@input-padding-vertical-base': '8px',
  '@input-padding-vertical-lg': '12px',
  '@input-padding-horizontal-lg': '12px',
  '@form-item-margin-bottom': '20px',
  '@layout-header-background': colors.blue[900],
  '@layout-sider-background': colors.blue[900],
  '@menu-item-boundary-margin': 0,
  '@menu-item-vertical-margin': 0,
  '@menu-dark-bg': colors.blue[900],
  '@menu-dark-submenu-bg': colors.blue[900],
  '@menu-dark-arrow-color': '#dee2e6',
  '@pagination-item-size-sm': '32px',
  '@pagination-item-size': '40px',
  '@dropdown-line-height': '32px',
  '@select-dropdown-height': '46px',
  '@dropdown-vertical-padding': '7px',
}
